---
steps:
  - label: ":pipeline: Test"
    agents:
      jdk7: "true"
    command: .buildkite/build.sh test
  - wait
  - label: ":pipeline: Deploy"
    agents:
      jdk7: "true"
    command: .buildkite/build.sh deploy
